version: "3"

services:
  pg:
    build:
      dockerfile: pg.Dockerfile
    ports:
      - "5433:5432"
    env_file:
      - ./env.env
    volumes:
      - ./.pg_data:/var/lib/postgresql/data

  app:
    build:
      dockerfile: app.Dockerfile
    command: >
      bash -c "while !</dev/tcp/pg/5432; do sleep 1; done; python manage.py collectstatic --no-input && python manage.py migrate --fake rate 0001 && python manage.py migrate && gunicorn main.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - env.env
    volumes:
      - static_volume:/xeneta-ratetask/staticfiles
    depends_on:
      - pg

  nginx:
    image: "nginx:alpine"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/xeneta-ratetask/staticfiles
    depends_on:
      - app

volumes:
  static_volume:
