# Generated by Django 4.1.5 on 2023-01-07 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='port code')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'ports',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('slug', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('parent', models.ForeignKey(blank=True, db_column='parent_slug', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rate.region')),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('price', models.IntegerField()),
                ('dest_code', models.ForeignKey(db_column='dest_code', on_delete=django.db.models.deletion.DO_NOTHING, related_name='prices_to', to='rate.port')),
                ('orig_code', models.ForeignKey(db_column='orig_code', on_delete=django.db.models.deletion.DO_NOTHING, related_name='prices_from', to='rate.port')),
            ],
            options={
                'db_table': 'prices',
            },
        ),
        migrations.AddField(
            model_name='port',
            name='parent',
            field=models.ForeignKey(db_column='parent_slug', on_delete=django.db.models.deletion.DO_NOTHING, to='rate.region'),
        ),
    ]
